// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58317Mr1CvlUPXky6lrpBfAFjVpJWYto',
    appId: '1:690565796259:web:90f36d384ba309328dca16',
    messagingSenderId: '690565796259',
    projectId: 'project-1-469ba',
    authDomain: 'project-1-469ba.firebaseapp.com',
    storageBucket: 'project-1-469ba.firebasestorage.app',
    measurementId: 'G-T5JW9D5EQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbW2pGMccd5Rj3SUyHDjUyG5wRDmh3Os',
    appId: '1:690565796259:android:ea56bd3c362dea068dca16',
    messagingSenderId: '690565796259',
    projectId: 'project-1-469ba',
    storageBucket: 'project-1-469ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgc_k9gsEYPmBecx2aa2S5K9q9r90Mc2Q',
    appId: '1:690565796259:ios:f2da7bab88e748588dca16',
    messagingSenderId: '690565796259',
    projectId: 'project-1-469ba',
    storageBucket: 'project-1-469ba.firebasestorage.app',
    iosBundleId: 'com.example.sginUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgc_k9gsEYPmBecx2aa2S5K9q9r90Mc2Q',
    appId: '1:690565796259:ios:f2da7bab88e748588dca16',
    messagingSenderId: '690565796259',
    projectId: 'project-1-469ba',
    storageBucket: 'project-1-469ba.firebasestorage.app',
    iosBundleId: 'com.example.sginUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD58317Mr1CvlUPXky6lrpBfAFjVpJWYto',
    appId: '1:690565796259:web:dfa0b66be340db468dca16',
    messagingSenderId: '690565796259',
    projectId: 'project-1-469ba',
    authDomain: 'project-1-469ba.firebaseapp.com',
    storageBucket: 'project-1-469ba.firebasestorage.app',
    measurementId: 'G-QZEQLYX3L2',
  );
}
